beginner/feed/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView

app_name = "feed"

urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("detail/<int:pk>/", PostDetailView.as_view(), name="detail"),
    path("post/", AddPostView.as_view(), name="post")
]

beginner/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beginner/feed/models.py
from django.db import models
from sorl.thumbnail import ImageField

class Post(models.Model):
    text = models.CharField(max_length=140, null=False, blank=False)
    image = ImageField()

    def __str__(self):
        return self.text

beginner/feed/forms.py
from django import forms

class PostForm(forms.Form):
    image = forms.ImageField()
    text = forms.CharField(label="Caption")

beginner/feed/views.py
from django.contrib import messages
from django.views.generic import TemplateView, DetailView, FormView
from .models import Post
from .forms import PostForm

class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["posts"] = Post.objects.all().order_by('-id')
        return context

class PostDetailView(DetailView):
    template_name = "detail.html"
    model = Post

class AddPostView(FormView):
    template_name = "new_post.html"
    form_class = PostForm
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        new_object = Post.objects.create(
            text=form.cleaned_data['text'],
            image=form.cleaned_data['image']
        )

        messages.add_message(self.request, messages.SUCCESS, "Your post was successful!!!")
        return super().form_valid(form)

beginner/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>{% block title %}Default Title {% endblock %}</title>
</head>
<body>
    {% include 'includes/navbar.html' %}

    <div class="container">
        {% block body %} Hello world {% endblock %}
    </div>
</body>
</html>

beginner/templates/detail.html
{% extends "base.html" %}

{% block title %}Detailed View{% endblock %}

{% block body %}
    <a href="{% url 'feed:index' %}">&lAarr; Go back</a>
    <div class="row">
        <div class="col-sm-10 offset-sm-1 py-5">
           {{ object.text  }}
            <img src="{{ object.image.url }}", class="img-fluid rounded" width="100%", height="auto">
        </div>
    </div>



{% endblock %}

beginner/templates/home.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}My super awesome home page{% endblock %}

{% block body %}

{% if messages %}
    {% for message in messages %}
        <div class="bg-{% if message.tags %}{{ message.tags }}{% else %}}success{% endif %} bg-gradiant py-3 text-center text-white">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}


<div class="row">
{% for post in posts %}
    <div class ="col-sm-6 col-md-4 py-3">
        <div class="card" style="width: 18rem;">
            {% thumbnail post.image "200x200" crop="center" as im %}
                <img src="{{ im.url }}" class="card-img-top" alt="...">
            {% endthumbnail %}
            <div class="card-body">
                <p class="card-text">{{ post.text }}</p>
                <a href="{% url 'feed:detail' post.id %}" class="btn btn-primary">Go to full size image</a>
            </div>
        </div>
    </div>
    {% empty %}
        <div class="col-sm-4 offset-sm-4 py-5 my-5">
            <h3>Welcome!</h3>
            <p>Add your first image?</p>
            <a href="{% url 'feed:post' %}" class="btn btn-lg btn-success">Add image</a>
        </div>
{% endfor %}
</div>



{% endblock %}

beginner/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'feed:index' %}">Image Sharer</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'feed:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'feed:post' %}">Add new post</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

beginner/templates/new_post.html
{% extends "base.html" %}

{% block title %}Add a new post{% endblock %}

{% block body %}

<form method="POST" action="" enctype="multipart/form-data" class="col-sm-4 offset-sm-4 py-5">
    <h2>Upload an image!</h2>
    {% csrf_token %}
    {{ form.as_p }}
    <div>
        <button type="submit", class="btn btn-lg btn-success">Submit form</button>
    </div>
</form>


{% endblock %}