intermediate/feed/urls.py
from django.urls import path
from . import views

app_name = "feed"

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
    path("<int:pk>/", views.DetailedPostView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
]

intermediate/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from feed import urls as feed_urls
from profiles import urls as profiles_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path("profile/", include(profiles_urls, namespace="profiles")),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intermediate/templates/components/sidebar_nav.html
<!-- component -->
<div class="flex flex-col min-w-44 max-w-72 w-2/12 bg-white rounded-r-3xl overflow-hidden">
    <div class="flex items-center justify-center h-20 shadow-md">
        <h1 class="text-3xl uppercase text-indigo-500">TIL</h1>
    </div>
    <ul class="flex flex-col py-4">
        <li>
            <a href="{% url 'feed:index' %}"
               class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                        <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i
                                class="bx bx-home"></i></span>
                <span class="text-sm font-medium">Home</span>
            </a>
        </li>
        {% if request.user.is_authenticated %}
            <li>
                <a href="{% url 'feed:new_post' %}"
                   class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800 js-toggle-modal">
                            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i
                                    class="bx bx-layer-plus"></i></span>
                    <span class="text-sm font-medium">Add Post</span>
                </a>
            </li>
            <li>
                <a href="{% url 'profiles:detail' user.username %}"
                   class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i
                                    class="bx bx-edit"></i></span>
                    <span class="text-sm font-medium">View Profile</span>
                </a>
            </li>
            <li>
                <a href="{% url 'account_logout' %}"
                   class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i
                                    class="bx bx-log-out"></i></span>
                    <span class="text-sm font-medium">Logout</span>
                </a>
            </li>
        {% else %}
            <li>
                <a href="{% url 'account_login' %}"
                   class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i
                                    class="bx bx-log-in"></i></span>
                    <span class="text-sm font-medium">Login</span>
                </a>
            </li>
        {% endif %}
    </ul>
</div>