intermediate/feed/urls.py
from django.urls import path
from . import views

app_name = "feed"

urlpatterns = [
    path("", views.HomePage.as_view(), name="index"),
    path("<int:pk>/", views.DetailedPostView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
]

intermediate/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from feed import urls as feed_urls
from profiles import urls as profiles_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path("profile/", include(profiles_urls, namespace="profiles")),
    path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intermediate/profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"

urlpatterns = [
    path("<str:username>/", views.ProfileDetailView.as_view(), name="detail"),
    path("<str:username>/edit/", views.ProfileEdit.as_view(), name="edit"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
]

intermediate/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE
    )
    profile_name = models.CharField(max_length=100)
    image = ImageField(upload_to='profiles')

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

intermediate/profiles/views.py
from django.contrib.auth.models import User
from django.views.generic import DetailView, View, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.urls import reverse_lazy

from feed.models import Post
from followers.models import Follower
from profiles.models import Profile


from django.forms import modelformset_factory
# AuthorFormSet = modelformset_factory(Author, fields=["name", "title"])


class ProfileDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "profiles/detail.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        user = self.get_object()
        context = super().get_context_data(**kwargs)
        context['total_posts'] = Post.objects.filter(author=user).count()
        context['total_followers'] = Follower.objects.filter(following=user).count()

        if self.request.user.is_authenticated:
            context['you_follow'] = Follower.objects.filter(following=user, followed_by=self.request.user,).exists()

        return context


class MultiUpdateMixin:
    # A class that creates an update view that gets multiple model sources
    # and also puts to multiple model sources.

    def get(self, request, *args, **kwargs):
        context = {}
        for i in range(len(self.models)):
            self.object = self.get_object(i)
            context[self.context_object_name] = self.get_context_data()
        return self.render_to_response(self.transform_context(context))

    def transform_context(self, context):
        # Remap the context dictionary to have key values in the following form
        #   object.model_n....
        #   model_1
        #   model_2
        #   form.model_n...
        #   view
        new_context = {}
        new_context["object"] = {}
        new_context["form"] = {}
        for context_object_name in self.context_object_names:
            new_context["object"][context_object_name] = context[context_object_name]["object"]
            new_context["form"][context_object_name] = context[context_object_name]["form"]
            new_context[context_object_name] = context[context_object_name][context_object_name]
            new_context.setdefault("view", context[context_object_name]["view"])
        return new_context

    def post(self, request, *args, **kwargs):
        valid_forms = []
        for i in range(len(self.models)):
            self.object = self.get_object(i)
            form = self.get_form()
            if form.is_valid():
                valid_forms.append(form)
            else:
                return self.get(request, *args, **kwargs)

        for i, form in enumerate(valid_forms):
            self.object = self.get_object(i)
            self.object = form.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_object(self, i):
        self.slug_field = self.slug_fields[i]
        self.model = self.models[i]
        self.fields = self.fields_all[i]
        self.context_object_name = self.context_object_names[i]
        return super().get_object()


class ProfileEdit(LoginRequiredMixin, MultiUpdateMixin, UpdateView):
    http_method_names = ['get', 'post']
    models = [Profile, User]
    context_object_names = ["profile", "user"]
    slug_url_kwarg = "username"
    slug_fields = ["user__username", "username"]

    fields_all = [
        [
            "image",
            "profile_name"
        ],
        [
            "username",
            "password",
            "first_name",
            "last_name",
        ],

    ]
    template_name = "profiles/edit.html"

    def get_success_url(self):
        self.success_url = reverse_lazy("profiles:detail", args=[self.object.username])
        return super().get_success_url()


class FollowView(LoginRequiredMixin, View):
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()

        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("Missing data")

        try:
            other_user = User.objects.get(username=data['username'])
        except User.DoesNotExist:
            return HttpResponseBadRequest("Missing data")

        if data['action'] == 'follow':
            follower, created = Follower.objects.get_or_create(
                followed_by=request.user,
                following=other_user,
            )
        else:
            try:
                follower = Follower.objects.get(
                    followed_by=request.user,
                    following=other_user,
                )
            except Follower.DoesNotExist:
                follower = None

            if follower:
                follower.delete()

        return JsonResponse({
            'success': True,
            'wording': "Unfollow" if data['action'] == "follow" else "Follow"
        })

intermediate/templates/profiles/detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %} {{ user.username }}{% endblock title %}

{% block body %}
    <div class="h-fit rounded-3xl overflow-hidden shadow-xl w-72 my-3 bg-blue-500">
        {% if request.user == user %}
            <div class="flex justify-center">
                <a class="text-blue-600 rounded-xl min-h-8 my-1 p-2 bg-white" href="{% url 'profiles:edit' user.username %}">Edit profile</a>
            </div>
        {% else %}
            <h3 class="my-1 min-h-8"></h3>
        {% endif %}
        <div class="w-full mt-12"></div>

        <div class="flex justify-center -mt-8">
            {% thumbnail user.profile.image "100x100" crop="center" as im %}
                <img src="{{ im.url }}" class="rounded-full border-solid border-white border-2 -mt-3">
            {% endthumbnail %}
        </div>
        <div class="text-center px-3 pb-6 pt-2">
            <h3 class="text-white text-sm bold font-sans">{{ user.username }}</h3>
            {% if request.user.is_authenticated %}
                {% if request.user != user %}
                    <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-1 px-3 inline-flex items-center text-sm mt-4 js-follow"
                            data-action="{% if you_follow %}un{% endif %}follow"
                            data-url="{% url 'profiles:follow' user.username %}"
                            data-username="{{ user.username }}" type="button">
                        <span class="mr-2 js-follow-text">
                            {% if you_follow %}
                                Unfollow
                            {% else %}
                                Follow
                            {% endif %}
                        </span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                            <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                        </svg>
                    </button>
                {% endif %}
            {% else %}
                <div class="mt-3 text-small text-white">Login to follow this user</div>
            {% endif %}
        </div>
        <div class="flex justify-center pb-3 text-white">
            <div class="text-center mr-3 border-r pr-3">
                <h2>{{ total_posts }}</h2>
                <span>Posts</span>
            </div>
            <div class="text-center">
                <h2>{{ total_followers }}</h2>
                <span>Followers</span>
            </div>
        </div>
    </div>


{% endblock body %}

intermediate/templates/profiles/edit.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% load thumbnail %}

{% block title %} {{ user.username }} edit {% endblock title %}

{% block body %}
    <div style="background-color : #f4f4f0" class=" sm:mx-32 lg:mx-32 xl:mx-72 ">
        <div class="flex justify-between container mx-auto">
            <div class="w-full">
                <div class="mt-4 px-4">
                    <h1 class="font-thinner flex text-4xl pt-10 px-5">
                        Edit your profile
                    </h1>

                    <form method="post" enctype="multipart/form-data" class="mx-5 my-5">
                        {% csrf_token %}
                        <label class="relative block my-2 p-3 border-2 border-black rounded" htmlFor="name">
                              <span class="text-md font-semibold text-zinc-900" htmlFor="name">
                                Username
                              </span>
                            {% render_field form.user.username class="w-full bg-transparent p-0 text-sm  text-gray-500 focus:outline-none" placeholder="My username" %}
                        </label>
                        <label class="relative block my-2 p-3 border-2 border-black rounded" htmlFor="name">
                              <span class="text-md font-semibold text-zinc-900" htmlFor="name">
                                Password
                              </span>
                            {% render_field form.user.password type='password' class="w-full bg-transparent p-0 text-sm  text-gray-500 focus:outline-none" placeholder="My password" %}
                        </label>
                        <label class="relative block my-2 p-3 border-2 border-black rounded" htmlFor="name">
                            <span class="text-md font-semibold text-zinc-900" htmlFor="name">
                                First Name
                              </span>
                            {% render_field form.user.first_name class="w-full bg-transparent p-0 text-sm  text-gray-500 focus:outline-none" placeholder="My first name" %}

                        </label>
                        <label class="relative block my-2 p-3 border-2 border-black rounded" htmlFor="name">
                            <span class="text-md font-semibold text-zinc-900" htmlFor="name">
                                Last Name
                              </span>
                            {% render_field form.user.last_name class="w-full bg-transparent p-0 text-sm  text-gray-500 focus:outline-none" placeholder="My last name" %}
                        </label>
                        <label class="relative block my-2 p-3 border-2 border-black rounded" htmlFor="name">
                            <span class="text-md font-semibold text-zinc-900" htmlFor="name">
                                Profile Name
                              </span>
                            {% render_field form.profile.profile_name class="w-full bg-transparent p-0 text-sm  text-gray-500 focus:outline-none" placeholder="My profile name" %}
                        </label>


                        <div class="shrink-0 mt-5">
                            {% thumbnail profile.image "100x100" crop="center" as im %}
                                <img src="{{ im.url }}" class="h-20 w-20 object-cover rounded-full"
                                     alt="Current profile photo">
                            {% endthumbnail %}
                        </div>
                        <label class="block pt-2">
                            <span class="sr-only t-2">Choose profile photo</span>
                            {% render_field form.profile.image type='file' name='image' class="w-full text-sm text-slate-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-pink-300 file:text-zinc-900 hover:file:bg-rose-300" %}
                        </label>


                        <button type='submit'
                                class="mt-5 border-2 px-5 py-2 rounded-lg border-black border-b-4 font-black translate-y-2 border-l-4">
                            Submit
                        </button>
                    </form>
                </div>
            </div>


        </div>
    </div>
    </div>
{% endblock body %}